
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Battery, Zap, AlertTriangle, Home, Clock, DollarSign, Check, Info } from 'lucide-react';

interface SolarBatteryStorageProps {
  onComplete: () => void;
}

const SolarBatteryStorage: React.FC<SolarBatteryStorageProps> = ({ onComplete }) => {
  const [isCompleted, setIsCompleted] = useState(false);
  const [batteryLevel, setBatteryLevel] = useState(0);
  const [activeTab, setActiveTab] = useState('overview');
  
  // Animate battery filling up
  React.useEffect(() => {
    const timer = setTimeout(() => {
      if (batteryLevel < 100) {
        setBatteryLevel(prev => Math.min(prev + 1, 100));
      }
    }, 20);
    
    return () => clearTimeout(timer);
  }, [batteryLevel]);

  const handleComplete = () => {
    setIsCompleted(true);
    onComplete();
  };

  return (
    <div className="space-y-8">
      <div className="text-center mb-6">
        <h2 className="text-2xl font-bold text-gray-800">Battery Storage</h2>
        <p className="text-gray-600 mt-2">Understanding energy storage options for your solar system.</p>
      </div>

      <div className="flex justify-center mb-8">
        <div className="relative w-32 h-64">
          <motion.div 
            className="absolute inset-0 border-4 border-gray-300 rounded-lg overflow-hidden"
            animate={{ borderColor: batteryLevel > 90 ? '#10b981' : '#3b82f6' }}
          >
            <motion.div 
              className="absolute bottom-0 left-0 right-0 bg-energy-blue"
              animate={{ 
                height: `${batteryLevel}%`,
                backgroundColor: batteryLevel > 90 ? '#10b981' : '#3b82f6'
              }}
              transition={{ duration: 0.5 }}
            />
            
            <div className="absolute inset-0 flex flex-col items-center justify-center text-white font-bold text-2xl">
              {batteryLevel}%
            </div>
          </motion.div>
          
          <motion.div 
            className="absolute -top-4 left-1/2 transform -translate-x-1/2 w-16 h-4 bg-gray-300 rounded-t-md"
            animate={{ backgroundColor: batteryLevel > 90 ? '#10b981' : '#3b82f6' }}
          />
        </div>
      </div>

      <div className="flex justify-center mb-6">
        <div className="grid grid-cols-3 gap-1 bg-gray-100 p-1 rounded-lg">
          <button
            onClick={() => setActiveTab('overview')}
            className={`px-4 py-2 text-sm rounded-md transition-all ${
              activeTab === 'overview'
                ? 'bg-white shadow-sm text-energy-blue'
                : 'text-gray-600 hover:bg-gray-200'
            }`}
          >
            Overview
          </button>
          <button
            onClick={() => setActiveTab('benefits')}
            className={`px-4 py-2 text-sm rounded-md transition-all ${
              activeTab === 'benefits'
                ? 'bg-white shadow-sm text-energy-blue'
                : 'text-gray-600 hover:bg-gray-200'
            }`}
          >
            Benefits
          </button>
          <button
            onClick={() => setActiveTab('costs')}
            className={`px-4 py-2 text-sm rounded-md transition-all ${
              activeTab === 'costs'
                ? 'bg-white shadow-sm text-energy-blue'
                : 'text-gray-600 hover:bg-gray-200'
            }`}
          >
            Costs
          </button>
        </div>
      </div>

      <AnimatePresence mode="wait">
        {activeTab === 'overview' && (
          <motion.div
            key="overview"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            transition={{ duration: 0.3 }}
            className="bg-white p-6 rounded-lg shadow-sm border border-gray-100"
          >
            <h3 className="text-xl font-semibold mb-4">What is Battery Storage?</h3>
            <p className="text-gray-700 mb-4">
              Battery storage systems allow you to store excess electricity generated by your solar panels during the day,
              so you can use it when the sun isn't shining. This provides energy security, helps maximize your solar investment,
              and can even allow you to go "off-grid" in some cases.
            </p>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6">
              <div className="bg-blue-50 p-4 rounded-lg">
                <div className="flex items-center mb-2">
                  <Clock className="w-5 h-5 text-blue-600 mr-2" />
                  <h4 className="font-medium">Time Shifting</h4>
                </div>
                <p className="text-sm text-gray-600">
                  Use your own solar energy during evening peak rate hours instead of buying expensive grid power.
                </p>
              </div>
              
              <div className="bg-green-50 p-4 rounded-lg">
                <div className="flex items-center mb-2">
                  <AlertTriangle className="w-5 h-5 text-green-600 mr-2" />
                  <h4 className="font-medium">Backup Power</h4>
                </div>
                <p className="text-sm text-gray-600">
                  Keep essential appliances running during blackouts and power outages.
                </p>
              </div>
              
              <div className="bg-purple-50 p-4 rounded-lg">
                <div className="flex items-center mb-2">
                  <DollarSign className="w-5 h-5 text-purple-600 mr-2" />
                  <h4 className="font-medium">Energy Independence</h4>
                </div>
                <p className="text-sm text-gray-600">
                  Reduce reliance on the utility grid and protect yourself from rate increases.
                </p>
              </div>
            </div>
          </motion.div>
        )}
        
        {activeTab === 'benefits' && (
          <motion.div
            key="benefits"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            transition={{ duration: 0.3 }}
            className="bg-white p-6 rounded-lg shadow-sm border border-gray-100"
          >
            <h3 className="text-xl font-semibold mb-4">Benefits of Battery Storage</h3>
            
            <div className="space-y-4">
              <div className="flex">
                <div className="mr-4 mt-1">
                  <div className="w-6 h-6 bg-green-100 rounded-full flex items-center justify-center">
                    <Check className="w-4 h-4 text-green-600" />
                  </div>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900">Protection During Power Outages</h4>
                  <p className="text-gray-600">
                    Battery storage provides backup power during grid outages, keeping essential appliances and systems running.
                    This is especially valuable in California where wildfires and Public Safety Power Shutoffs are common.
                  </p>
                </div>
              </div>
              
              <div className="flex">
                <div className="mr-4 mt-1">
                  <div className="w-6 h-6 bg-green-100 rounded-full flex items-center justify-center">
                    <Check className="w-4 h-4 text-green-600" />
                  </div>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900">Maximize Self-Consumption</h4>
                  <p className="text-gray-600">
                    Under California's NEM 3.0, selling excess power to the grid provides less value. Batteries let you store that energy
                    and use it when needed, increasing your solar system's value.
                  </p>
                </div>
              </div>
              
              <div className="flex">
                <div className="mr-4 mt-1">
                  <div className="w-6 h-6 bg-green-100 rounded-full flex items-center justify-center">
                    <Check className="w-4 h-4 text-green-600" />
                  </div>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900">Avoid Peak Rate Charges</h4>
                  <p className="text-gray-600">
                    Utility companies charge more during peak hours (typically evenings). Batteries let you avoid these high rates
                    by using stored solar energy when rates are highest.
                  </p>
                </div>
              </div>
              
              <div className="flex">
                <div className="mr-4 mt-1">
                  <div className="w-6 h-6 bg-green-100 rounded-full flex items-center justify-center">
                    <Check className="w-4 h-4 text-green-600" />
                  </div>
                </div>
                <div>
                  <h4 className="font-medium text-gray-900">Federal Tax Credits</h4>
                  <p className="text-gray-600">
                    Standalone battery installations now qualify for the federal tax credit (30% of system cost),
                    making battery storage more affordable than ever.
                  </p>
                </div>
              </div>
            </div>
          </motion.div>
        )}
        
        {activeTab === 'costs' && (
          <motion.div
            key="costs"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            transition={{ duration: 0.3 }}
            className="bg-white p-6 rounded-lg shadow-sm border border-gray-100"
          >
            <h3 className="text-xl font-semibold mb-4">Cost Considerations</h3>
            
            <div className="mb-6">
              <h4 className="font-medium text-gray-900 mb-2">Average Battery System Costs</h4>
              <div className="bg-gray-100 p-4 rounded-lg">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Entry-Level System</p>
                    <p className="text-xl font-bold text-gray-900">$8,000 - $12,000</p>
                    <p className="text-xs text-gray-500">After 30% tax credit</p>
                  </div>
                  <div>
                    <p className="text-sm text-gray-600 mb-1">Whole-Home Backup</p>
                    <p className="text-xl font-bold text-gray-900">$15,000 - $30,000</p>
                    <p className="text-xs text-gray-500">After 30% tax credit</p>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="mb-6">
              <h4 className="font-medium text-gray-900 mb-2">When Does Battery Storage Make Financial Sense?</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <span className="text-energy-blue mr-2">•</span>
                  <span>If you experience frequent power outages or live in a high fire-risk area</span>
                </li>
                <li className="flex items-start">
                  <span className="text-energy-blue mr-2">•</span>
                  <span>If your utility has high peak-time rates (significant price difference between day and night rates)</span>
                </li>
                <li className="flex items-start">
                  <span className="text-energy-blue mr-2">•</span>
                  <span>If your utility offers battery incentive programs (like SGIP in California)</span>
                </li>
                <li className="flex items-start">
                  <span className="text-energy-blue mr-2">•</span>
                  <span>If energy independence is a primary goal, regardless of cost</span>
                </li>
              </ul>
            </div>
            
            <div className="bg-yellow-50 p-4 rounded-lg">
              <div className="flex items-start">
                <Info className="w-5 h-5 text-yellow-600 mt-0.5 mr-3 flex-shrink-0" />
                <p className="text-sm text-yellow-700">
                  Battery costs have been declining each year, and with increasing utility rates and incentive programs,
                  the financial case for batteries is becoming stronger. We recommend getting updated pricing when you
                  request your solar quote.
                </p>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="flex justify-center mt-6">
        <Button 
          onClick={handleComplete}
          disabled={isCompleted}
          className={`px-8 ${isCompleted ? 'bg-green-500' : 'bg-energy-blue'}`}
        >
          {isCompleted ? 'Completed!' : 'I Understand Battery Options'}
        </Button>
      </div>
    </div>
  );
};

// AnimatePresence is not directly imported, so we need to create a simple version
const AnimatePresence: React.FC<{
  children: React.ReactNode;
  mode?: 'sync' | 'wait';
}> = ({ children }) => {
  return <>{children}</>;
};

export default SolarBatteryStorage;
